<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" name="Getting_Account_Transaction_List" targetNamespace="http://VMTComponentModel/InterfaceSpecification/Interfaces/C4/VMTtoFSPService" xmlns:c4="http://VMTComponentModel/InterfaceSpecification/FSPDefined/Messages/C4/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:vmt="http://VMTComponentModel/InterfaceSpecification/Interfaces/C4/VMTtoFSPService" xmlns:vmt1="http://schemas.datacontract.org/2004/07/VMT.BankingIntegration.FSIC4Simulator.Common" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <wsdl:documentation>
    <wsdl:appinfo source="WMQI_APPINFO">
      <MRWSDLAppInfo imported="true">
        <binding hasEncoding="false" imported="true" name="Getting_Account_Transaction_ListSOAP" originalBindingStyle="document"/>
        <generatedXSD location="Getting_Account_Transaction_List_InlineSchema1.xsd"/>
        <generatedXSD location="Getting_Account_Transaction_List_InlineSchema3.xsd"/>
        <generatedXSD location="Getting_Account_Transaction_List_InlineSchema2.xsd"/>
      </MRWSDLAppInfo>
    </wsdl:appinfo>
  </wsdl:documentation>
  
  <wsdl:types>
    
    
    
    
          <xsd:schema attributeFormDefault="qualified" elementFormDefault="qualified" targetNamespace="http://VMTComponentModel/InterfaceSpecification/Interfaces/C4/VMTtoFSPService" xmlns:ibmSchExtn="http://www.ibm.com/schema/extensions">
<xsd:import namespace="http://VMTComponentModel/InterfaceSpecification/FSPDefined/Messages/C4/" schemaLocation="Getting_Account_Transaction_List_InlineSchema2.xsd"/>
<xsd:include schemaLocation="Getting_Account_Transaction_List_InlineSchema1.xsd"/>
</xsd:schema>
        <xsd:schema attributeFormDefault="qualified" elementFormDefault="qualified" targetNamespace="http://schemas.datacontract.org/2004/07/VMT.BankingIntegration.FSIC4Simulator.Common">

<xsd:include schemaLocation="Getting_Account_Transaction_List_InlineSchema3.xsd"/>
</xsd:schema>
        <xsd:schema attributeFormDefault="qualified" elementFormDefault="qualified" targetNamespace="http://VMTComponentModel/InterfaceSpecification/FSPDefined/Messages/C4/">
<xsd:import namespace="http://schemas.datacontract.org/2004/07/VMT.BankingIntegration.FSIC4Simulator.Common" schemaLocation="Getting_Account_Transaction_List_InlineSchema3.xsd"/>
<xsd:include schemaLocation="Getting_Account_Transaction_List_InlineSchema2.xsd"/>
</xsd:schema>
    </wsdl:types>
  <wsdl:message name="GetAccountTransactionListRequest">
    <wsdl:part element="vmt:GetAccountTransactionList" name="parameters"/>
  </wsdl:message>
  <wsdl:message name="GetAccountTransactionListResponse">
    <wsdl:part element="vmt:GetAccountTransactionListResponse" name="parameters"/>
  </wsdl:message>
  <wsdl:portType name="Getting_Account_Transaction_List">
    <wsdl:operation name="GetAccountTransactionList">
      <wsdl:input message="vmt:GetAccountTransactionListRequest"/>
      <wsdl:output message="vmt:GetAccountTransactionListResponse"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="Getting_Account_Transaction_ListSOAP" type="vmt:Getting_Account_Transaction_List">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="GetAccountTransactionList">
      <soap:operation soapAction="http://VMTComponentModel/InterfaceSpecification/Interfaces/C4/VMTtoFSPService/NewOperation"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="Getting_Account_Transaction_List">
    <wsdl:port binding="vmt:Getting_Account_Transaction_ListSOAP" name="Getting_Account_Transaction_ListSOAP">
      <soap:address location="http://www.example.org/"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>