<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" name="Activating_FSI_Product" targetNamespace="http://VMTComponentModel/InterfaceSpecification/Interfaces/C4/VMTtoFSPService" xmlns:c4="http://VMTComponentModel/InterfaceSpecification/FSPDefined/Messages/C4/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:vmt="http://VMTComponentModel/InterfaceSpecification/Interfaces/C4/VMTtoFSPService" xmlns:vmt1="http://schemas.datacontract.org/2004/07/VMT.BankingIntegration.FSIC4Simulator.Common" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <wsdl:documentation>
    <wsdl:appinfo source="WMQI_APPINFO">
      <MRWSDLAppInfo imported="true">
        <binding hasEncoding="false" imported="true" name="Activating_FSI_ProductSOAP" originalBindingStyle="document"/>
        <generatedXSD location="Activating_FSI_Product_InlineSchema1.xsd"/>
        <generatedXSD location="Activating_FSI_Product_InlineSchema2.xsd"/>
        <generatedXSD location="Activating_FSI_Product_InlineSchema3.xsd"/>
      </MRWSDLAppInfo>
    </wsdl:appinfo>
  </wsdl:documentation>
  
  <wsdl:types>
    
    
    
    
          <xsd:schema attributeFormDefault="qualified" elementFormDefault="qualified" targetNamespace="http://VMTComponentModel/InterfaceSpecification/Interfaces/C4/VMTtoFSPService" xmlns:ibmSchExtn="http://www.ibm.com/schema/extensions">
<xsd:import namespace="http://VMTComponentModel/InterfaceSpecification/FSPDefined/Messages/C4/" schemaLocation="Activating_FSI_Product_InlineSchema2.xsd"/>
<xsd:include schemaLocation="Activating_FSI_Product_InlineSchema1.xsd"/>
</xsd:schema>
        <xsd:schema attributeFormDefault="qualified" elementFormDefault="qualified" targetNamespace="http://VMTComponentModel/InterfaceSpecification/FSPDefined/Messages/C4/">
<xsd:import namespace="http://schemas.datacontract.org/2004/07/VMT.BankingIntegration.FSIC4Simulator.Common" schemaLocation="Activating_FSI_Product_InlineSchema3.xsd"/>
<xsd:include schemaLocation="Activating_FSI_Product_InlineSchema2.xsd"/>
</xsd:schema>
        <xsd:schema attributeFormDefault="qualified" elementFormDefault="qualified" targetNamespace="http://schemas.datacontract.org/2004/07/VMT.BankingIntegration.FSIC4Simulator.Common">

<xsd:include schemaLocation="Activating_FSI_Product_InlineSchema3.xsd"/>
</xsd:schema>
    </wsdl:types>
  <wsdl:message name="ActivateAccountRequest">
    <wsdl:part element="vmt:ActivateAccount" name="parameters"/>
  </wsdl:message>
  <wsdl:message name="ActivateAccountResponse">
    <wsdl:part element="vmt:ActivateAccountResponse" name="parameters"/>
  </wsdl:message>
  <wsdl:portType name="Activating_FSI_Product">
    <wsdl:operation name="ActivateAccount">
      <wsdl:input message="vmt:ActivateAccountRequest"/>
      <wsdl:output message="vmt:ActivateAccountResponse"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="Activating_FSI_ProductSOAP" type="vmt:Activating_FSI_Product">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="ActivateAccount">
      <soap:operation soapAction="http://VMTComponentModel/InterfaceSpecification/Interfaces/C4/VMTtoFSPService/NewOperation"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="Activating_FSI_Product">
    <wsdl:port binding="vmt:Activating_FSI_ProductSOAP" name="Activating_FSI_ProductSOAP">
      <soap:address location="http://127.0.0.1:7800/iib/cbemsl/activatingfsi"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>